### ISSUE TITLE
RgbdslamV2 depth picuture not working

### ISSUE THREAD

**Issue by mpresecan** [felixendres/rgbdslam_v2#1]
Hello,

I know that rgbdslam_v2 is in beta state, but somehow i cannot make it work properly.
I have hydro version of ROS, on Ubuntu 12.04, and i have installed it like on this tutorial:
http://felixendres.github.io/rgbdslam_v2/

when i run roslaunch rgbdslam openni+rgbdslam.launch
it opens GUI but it finds /camera/rgb/image_color but somehow it cannot subscribe on

>  /camera/depth_registered/sw_registered/image_rect_raw

Making rostopic echo of the topic, it gives me a values, and i can see the image on rviz.
But here on rgbdslam it cannot get the image.

Is this a bug, or settings are wrong? How can i solve the problem?

thank you
best

Michael

**Comment by felixendres** [comment]
If it displays the color image, it also gets the depth image. My guess is therefore that you only need to press space to start processing.

**Comment by mpresecan** [comment]
yes you are right!
Thank you, i just have to had change feature_detector_type and feature_extractor_type on SURF.

Thank you ones more
