### ISSUE TITLE
cmake error when executing catkin_make

### ISSUE THREAD

**Issue by FinleyPan** [felixendres/rgbdslam_v2#108]
My environment is Ubuntu 16.04. Everything goes well, but following error information appears once executing `catkin_make`:  
```
...
CMake Error at RGBDSLAMv2/CMakeLists.txt:236 (file):
  file GLOB requires a glob expression after the directory.
...
```
So I located line [236](https://github.com/felixendres/rgbdslam_v2/blob/kinetic/CMakeLists.txt#L236):
```
file(GLOB_RECURSE QT_SOURCES RELATIVE ${CMAKE_CURRENT_SOURCE_DIR} FOLLOW_SYMLINKS)
```
I think it should be 
```
file(GLOB_RECURSE QT_SOURCES RELATIVE ${CMAKE_CURRENT_SOURCE_DIR} FOLLOW_SYMLINKS <glob-expression>)
```
Why a glob expression is missing here?

**Comment by FinleyPan** [comment]
Solved by following update:
`file(GLOB_RECURSE QT_SOURCES RELATIVE ${CMAKE_CURRENT_SOURCE_DIR} FOLLOW_SYMLINKS "qt*")`

**Comment by ZhongKang97** [comment]
> Solved by following update: `file(GLOB_RECURSE QT_SOURCES RELATIVE ${CMAKE_CURRENT_SOURCE_DIR} FOLLOW_SYMLINKS "qt*")`

thanks, that works
