### ISSUE TITLE
why are my image drift went object dynamic ? help me plese .

### ISSUE THREAD

**Issue by supamon** [felixendres/rgbdslam_v2#12]
I can edit the problem?thank you My research, I use version rgbdslamv2.
picture http://image.ohozaa.com/view2/y9BCYXObWfxP7f6j

**Comment by kbalisciano** [comment]
Try moving back from the camera. In the depth map it looks like you have a little double vision due to the limitations of the camera

**Comment by supamon** [comment]
I don't understand. I want c++ file edit such as node.cpp.help me pleas. c-club-zaa@hotmail.com

**Comment by supamon** [comment]
c -club-zaa@hotmail.com

**Comment by supamon** [comment]
c-club-zaa@hotmail.com

**Comment by felixendres** [comment]
It seems the person is very near (less than 80cm) to the camera, therefore the visual features found on the person cannot be located in space and will be ignored. This reduces the amount of features available for estimating the motion. If part of the scene is dynamic the dynamic part may then easily "hijack" the motion estimation. Dynamic scenes are only handled well if the majority of the features are static. I usually had good results, even when people moved in the scene, but as I said, there neeed to be enough static features to "anchor" the motion estimates.
