### ISSUE TITLE
Error catkin_make

### ISSUE THREAD

**Issue by ziyangli** [felixendres/rgbdslam_v2#2]
I am using Hydro in Ubuntu12.04. When I try to make the pkg I come across the following error. I guess it is because the codes make use of deleted function boost::weak_ptr

/usr/include/c++/4.8/bits/stl_vector.h:920:36:   required from ‘void std::vector<_Tp, _Alloc>::push_back(std::vector<_Tp, _Alloc>::value_type&&) [with _Tp = boost::variantboost::weak_ptr<void, boost::signals2::detail::foreign_void_weak_ptr>; _Alloc = std::allocatorboost::variant<boost::weak_ptr<void, boost::signals2::detail::foreign_void_weak_ptr> >; std::vector<_Tp, _Alloc>::value_type = boost::variantboost::weak_ptr<void, boost::signals2::detail::foreign_void_weak_ptr>]’
/usr/include/boost/signals2/slot_base.hpp:93:55:   required from here
/usr/include/boost/variant/variant.hpp:401:9: error: use of deleted function ‘boost::weak_ptr<void>::weak_ptr(const boost::weak_ptr<void>&)’
         new(storage_) T( operand.get() );
         ^
In file included from /usr/include/boost/variant/variant.hpp:31:0,
                 from /usr/include/boost/signals2/slot_base.hpp:23,
                 from /usr/include/boost/signals2/detail/tracked_objects_visitor.hpp:18,
                 from /usr/include/boost/signals2/slot.hpp:22,
                 from /usr/include/boost/signals2/connection.hpp:23,
                 from /usr/include/boost/signals2/signal.hpp:21,
                 from /usr/include/boost/signals2.hpp:19,
                 from /usr/include/pcl-1.7/pcl/io/boost.h:73,
                 from /usr/include/pcl-1.7/pcl/io/file_io.h:43,
                 from /usr/include/pcl-1.7/pcl/io/pcd_io.h:44,
                 from /opt/ros/hydro/include/pcl_conversions/pcl_conversions.h:69,
                 from /opt/ros/hydro/include/pcl_ros/point_cloud.h:9,
                 from /home/zli-dji/ros/catkin_ws/build/rgbdslam/src/../../../src/rgbdslam/src/parameter_server.h:30,
                 from /home/zli-dji/ros/catkin_ws/build/rgbdslam/src/../../../src/rgbdslam/src/node.h:39,
                 from /home/zli-dji/ros/catkin_ws/build/rgbdslam/src/../../../src/rgbdslam/src/graph_manager.h:30,
                 from /home/zli-dji/ros/catkin_ws/build/rgbdslam/src/../../../src/rgbdslam/src/openni_listener.h:30,
                 from /home/zli-dji/ros/catkin_ws/build/rgbdslam/src/moc_openni_listener.cxx:10:
/usr/include/boost/variant/detail/initializer.hpp: In instantiation of ‘static int boost::detail::variant::make_initializer_node::apply<BaseIndexPair, Iterator>::initializer_node::initialize(void*, boost::detail::variant::make_initializer_node::apply<BaseIndexPair, Iterator>::initializer_node::param_T) [with BaseIndexPair = boost::mpl::pair<boost::detail::variant::initializer_root, mpl_::int_<0> >; Iterator = boost::mpl::l_iterboost::mpl::list2<boost::shared_ptr<void, boost::signals2::detail::foreign_void_shared_ptr> >; boost::detail::variant::make_initializer_node::apply<BaseIndexPair, Iterator>::initializer_node::param_T = const boost::shared_ptr<void>&]’:

**Comment by felixendres** [comment]
Interesting, I don't have this issue (also on Ubuntu 12.04). Is weak_ptr removed from boost because of the new C++0X standard?

**Comment by niosus** [comment]
@ziyangli I have bumped in the same issue. [Here](http://stackoverflow.com/questions/18900730/boostshared-ptrshared-ptrconst-boostshared-ptr-is-implicitly-declared) is what you are looking for. It states, that older versions of Boost (before 1.53) play badly with c++0x (c++11). The problem is a bug in Boost code, that implies, that if the move constructor is defined, the copy constructor would anyway be implicitly created. This is not the case for c++11.

It also only occurs with GNU compiler versions higher than 4.6 (with which standard Ubuntu 12.04 is shipped)
