### ISSUE TITLE
rosdep problem

### ISSUE THREAD

**Issue by kaygudo** [felixendres/rgbdslam_v2#24]
rosdep install rgbdslam_v2 yeilds:

ERROR: Rosdep cannot find all required resources to answer your query
Missing resource rgbdslam_v2
ROS path [0]=/opt/ros/indigo/share/ros
ROS path [1]=/opt/ros/indigo/share
ROS path [2]=/opt/ros/indigo/stacks

**Comment by felixendres** [comment]
Should be `rosdep install rgbdslam` without "_v2"

**Comment by kaygudo** [comment]
i m sorry the problem was with my catkin workspace setup. The package
worked from me amazingly :) . How does the package does localization? it
would b very kind of you.

with regards

**Comment by felixendres** [comment]
Please read the file README.md for usage information for the software and Chapter 3 of my [thesis](https://www.freidok.uni-freiburg.de/data/10239) if you'd like a description of the used algorithms.
