### ISSUE TITLE
rgbgslam_v2 (indigo) octomap geration of benchmark dataset

### ISSUE THREAD

**Issue by haobear** [felixendres/rgbdslam_v2#25]
I download a number of data from the link:

 http://vision.in.tum.de/data/datasets/rgbd-dataset

However, when I run generate_color_octomap_from_estimate.sh in rgbd_benchmark, I encountered the following error:
...........................................
...........................................
...........................................
[color_octomap_mapping_from_pcd.launch] is neither a launch file in package [octomap_server] nor is [octomap_server] a launch file name
The traceback for the exception was written to the log file
paul@paul-HP-Compaq-Elite-8300-SFF:~/rgbdslam_catkin_ws/src/rgbdslam_v2-indigo/rgbd_benchmark$ [rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done

Any ideas? Thanks!

**Comment by felixendres** [comment]
Hm, this is old stuff from when octomap's color mapping was experimental. Don't know how this would work now. You always can write a node to read in the pcd file and play back to the octomap_server. Or use the octomap library directly, as in rgbdslam/src/ColorOctomapServer.h/cpp.
