### ISSUE TITLE
Benchmark Dataset URLs obselete

### ISSUE THREAD

**Issue by petern3** [felixendres/rgbdslam_v2#40]
This is mostly for other users, but also for Felix if you feel like updating things.

I'm following the instructions on [Evaluation of the RGB-D SLAM system](http://wiki.ros.org/rgbdslam_electric/evaluation) (Section 3). When running download_benchmark_files.sh, it cannot find the urls (which are in [download_benchmark_data.urls](https://github.com/felixendres/rgbdslam_v2/blob/indigo/rgbd_benchmark/download_benchmark_data.urls)).

The dataset is now found at http://vision.in.tum.de/data/datasets/rgbd-dataset/download. You can either edit download_benchmark_data.urls, or manually download them into \[wherever rgbd_benchmark is\]/benchmark_data. (Make sure you pick the .bag files).

Also, the instructions to referring to ~/ros/rgbdslam/rgbd_benchmark/ could be changed to $(rospack find rgbdslam)/rgbd_benchmark/ so it works on more systems.

**Comment by felixendres** [comment]
Thanks for the information. These instructions are in the ROS wiki, so you could directly change the instructions. I fixed the urls (commit c91d612) in this repo, but I couldn't even checkout the svn repository (of my former university) anymore, so it's not going to change there.
