### ISSUE TITLE
How to get vodom from rgbdslam_v2

### ISSUE THREAD

**Issue by IrvingShu** [felixendres/rgbdslam_v2#46]
Hi, I want to get vodom and combine with imu data. But I want to know how to get vdom?Thank you.

**Comment by felixendres** [comment]
I am unsure what you mean. Probably the pose estimate (it is not an odometry estimate, but a SLAM estimate). You would get it via tf. There is a transformation from "map" to "openni_rgb_optical_frame", These names can be adapted using the parameters "fixed_frame_name" and "base_frame_name"
