### ISSUE TITLE
ERROR: Rosdep cannot find all required resources to answer your query

### ISSUE THREAD

**Issue by AIBluefisher** [felixendres/rgbdslam_v2#91]
Hi, @felixendres 
I put the rgbdslam_v2-kinetic in ~/catkin_ws/src/ directory, but when I execute rosdep install rgbdslam, the error occured

![selection_025](https://user-images.githubusercontent.com/18096136/37584721-932f4cb8-2b91-11e8-8e12-44e001fc6b1d.png)

I don't know what's going on, may you help me?
Thank you very much!

**Comment by mindThomas** [comment]
Do an initial `catkin_make` and let it fail.
Then source the workspace setup script: `source devel/setup.bash`
Now you should be able to install the dependencies using rosdep

**Comment by danielmessi13** [comment]
Not work for me

**Comment by OpalJellyfish** [comment]
This also does not work for me.
